Repository haru-speak/server, pull requests merged in 2023-02, with the labels that each got.

#90 APP LOGIN 방식 추가(추후 리팩토링 필요)
  be/src/main/java/com/example/be/oauth/config/KakaoAccountResponseDeserializer.java
  be/src/main/java/com/example/be/oauth/controller/LoginController.java
  be/src/main/java/com/example/be/oauth/provider/KakaoProvider.java
  be/src/main/java/com/example/be/oauth/provider/LoginService.java
  be/src/main/java/com/example/be/oauth/provider/client/KakaoMemberInfoClient.java
  be/src/main/java/com/example/be/oauth/provider/client/KakaoTokenClient.java
  be/src/main/java/com/example/be/oauth/provider/dto/request/LoginRequest.java
  be/src/main/java/com/example/be/oauth/provider/dto/response/KakaoAccessTokenResponse.java
  be/src/main/java/com/example/be/oauth/provider/dto/response/KakaoAccountResponse.java
  be/src/main/java/com/example/be/oauth/provider/dto/response/LoginResponse.java
  be/src/test/java/com/example/be/oauth/OAuthLoginIntegrationTest.java
Labels: ♻️ refactor, 🚨 Emergency

#92 멤버 Follow 요청 및 취소 기능 구현
  be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
  be/src/main/java/com/example/be/common/exception/member/InvalidSpeakingTestTypeException.java
  be/src/main/java/com/example/be/common/exception/member/NotFoundFollowRelationshipException.java
  be/src/main/java/com/example/be/common/exception/member/NotFoundMemberIdException.java
  be/src/main/java/com/example/be/common/exception/member/grade/InvalidSizeSpeakingGradeException.java
  be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
  be/src/main/java/com/example/be/core/application/MemberService.java
  be/src/main/java/com/example/be/core/application/dto/response/FollowResponse.java
  be/src/main/java/com/example/be/core/domain/member/Follow.java
  be/src/main/java/com/example/be/core/domain/member/SpeakingTestType.java
  be/src/main/java/com/example/be/core/repository/member/FollowRepository.java
  be/src/main/java/com/example/be/core/web/MemberController.java
  be/src/test/java/com/example/be/core/application/member/MemberFollowTest.java
  be/src/test/java/com/example/be/core/web/member/MemberControllerFollowTest.java
Labels: 🐣 feature

#98 Study API 관련 DTO 수정 및 추가
  be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
  be/src/main/java/com/example/be/common/exception/study/NotMatchStudyAndMemberException.java
  be/src/main/java/com/example/be/core/application/StudyService.java
  be/src/main/java/com/example/be/core/application/dto/response/MemberProfilesResponse.java
  be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
  be/src/main/java/com/example/be/core/application/dto/response/StudyPreviewResponse.java
  be/src/main/java/com/example/be/core/application/dto/response/StudyResponse.java
  be/src/main/java/com/example/be/core/domain/study/Study.java
  be/src/main/java/com/example/be/core/domain/study/StudyDayConverter.java
  be/src/main/java/com/example/be/core/domain/study/StudyFavorite.java
  be/src/main/java/com/example/be/core/domain/study/StudyRegion.java
  be/src/main/java/com/example/be/core/domain/study/StudyRegionConverter.java
  be/src/main/java/com/example/be/core/repository/study/StudyFavoriteRepository.java
  be/src/main/java/com/example/be/core/repository/study/StudyInterestRepository.java
  be/src/main/java/com/example/be/core/repository/study/StudyMemberRepository.java
  be/src/main/java/com/example/be/core/repository/study/StudyRepository.java
  be/src/main/java/com/example/be/core/web/StudyController.java
  be/src/test/java/com/example/be/core/application/assignment/AssignmentDetailFindTest.java
  be/src/test/java/com/example/be/core/application/study/StudyDeleteTest.java
  be/src/test/java/com/example/be/core/application/study/StudyFindAllTest.java
  be/src/test/java/com/example/be/core/application/study/StudyFindDetailTest.java
  be/src/test/java/com/example/be/core/application/study/StudyModifyTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerCreatTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerDeleteTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerDetailFindTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerFindByTypeTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerModifyTest.java
Labels: 🐣 feature

#103 목표 및 주제 전체 조회 기능 구현 및 테스트 완료
  be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
  be/src/main/java/com/example/be/core/application/dto/response/SubjectResponse.java
  be/src/main/java/com/example/be/core/application/member/GoalService.java
  be/src/main/java/com/example/be/core/application/member/MemberService.java
  be/src/main/java/com/example/be/core/application/member/SubjectService.java
  be/src/main/java/com/example/be/core/domain/member/subject/Subject.java
  be/src/main/java/com/example/be/core/web/member/GoalController.java
  be/src/main/java/com/example/be/core/web/member/MemberController.java
  be/src/main/java/com/example/be/core/web/member/SubjectController.java
  be/src/main/java/com/example/be/oauth/provider/LoginService.java
  be/src/test/java/com/example/be/core/application/goal_subject/GoalFindAllTest.java
  be/src/test/java/com/example/be/core/application/goal_subject/SubjectFindAllTest.java
  be/src/test/java/com/example/be/core/application/member/MemberFollowTest.java
  be/src/test/java/com/example/be/core/application/member/MemberModifyTest.java
  be/src/test/java/com/example/be/core/application/member/MemberMyPageTest.java
  be/src/test/java/com/example/be/core/application/member/MemberSignUpTest.java
  be/src/test/java/com/example/be/core/web/goal_subject/GoalControllerFindAllTest.java
  be/src/test/java/com/example/be/core/web/goal_subject/SubjectControllerFindAllTest.java
  be/src/test/java/com/example/be/core/web/member/MemberControllerFollowTest.java
  be/src/test/java/com/example/be/core/web/member/MemberControllerModifyTest.java
  be/src/test/java/com/example/be/core/web/member/MemberControllerMyPageTest.java
  be/src/test/java/com/example/be/core/web/member/MemberControllerSignUpTest.java
  be/src/test/java/com/example/be/tool/DataBaseConfigurator.java
Labels: 🐣 feature

#105 스터디 미리보기, 찜 컨트롤러, 서비스 로직 및 테스트 코드 작성
  be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
  be/src/main/java/com/example/be/common/exception/study/InvalidStudyPreviewTypeException.java
  be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
  be/src/main/java/com/example/be/core/application/StudyService.java
  be/src/main/java/com/example/be/core/application/dto/request/StudyConditionRequest.java
  be/src/main/java/com/example/be/core/application/dto/request/StudyPreviewConditionRequest.java
  be/src/main/java/com/example/be/core/application/dto/response/PreviewProfilesResponse.java
  be/src/main/java/com/example/be/core/application/dto/response/StudyPreviewResponse.java
  be/src/main/java/com/example/be/core/application/dto/response/StudyPreviewsResponse.java
  be/src/main/java/com/example/be/core/domain/study/StudyDay.java
  be/src/main/java/com/example/be/core/domain/study/StudyPreviewType.java
  be/src/main/java/com/example/be/core/domain/study/StudyType.java
  be/src/main/java/com/example/be/core/repository/study/StudyInterestRepository.java
  be/src/main/java/com/example/be/core/repository/study/StudyMemberRepository.java
  be/src/main/java/com/example/be/core/web/StudyController.java
  be/src/test/java/com/example/be/core/application/InitServiceTest.java
  be/src/test/java/com/example/be/core/application/study/StudyFindPreviewTest.java
  be/src/test/java/com/example/be/core/application/study/StudyInterestTest.java
  be/src/test/java/com/example/be/core/application/study/StudyNotInterestTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerFindByTypeTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerFindPreviewTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerInterestTest.java
  be/src/test/java/com/example/be/core/web/study/StudyControllerNotInterestTest.java
  be/src/test/java/com/example/be/tool/DataBaseConfigurator.java
Labels: 🐣 feature, 🧪 test
